import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./page.module.css"
import {ReactNode} from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.navbar}>
          <Link href={'/'} className={styles.navbarBtn}>Home</Link>
          <Link href={'/fun_fact'} className={styles.navbarBtn}>Fun fact</Link>
        </nav>
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
);
}
